### ISSUE TITLE
Setup doest work

### ISSUE THREAD

**Issue by WillRy** [kalimahapps/vue-options-to-composition#1]
Hello,

Firstly, thank you for the tool!

I would like to report a bug, in the "options api" there is the "setup" method, this method is not being converted correctly or I did something wrong!!!

Example: 

```js
    setup() {
        const alertState = useAlertStore();
        const timelineState = useTimelineStore();
        const {t} = useI18n();
        return {
            t,
            alertState: alertState,
            timelineState: timelineState
        };
    },
```

All the things inside the "setup" were not taken to the "composition api", where they were used they remained as "this.alertState" or "this.timelineState" and so on.

Thanks!

**Comment by abdul-alhasany** [comment]
`setup()` is part of composition api. 
https://vuejs.org/api/composition-api-setup.html
