### ISSUE TITLE
Chrome: does no conversion, loads some crazy stuff

### ISSUE THREAD

**Issue by d9k** [kalimahapps/vue-options-to-composition#3]
Seems it slowly loads all languages parsers instead of conversion... :unamused: 

![Selection_2024-07-02_02-10-57_01](https://github.com/kalimahapps/vue-options-to-composition/assets/7331988/a61101a9-3801-4edb-b98f-907b49af4b4d)
![Selection_2024-07-02_02-09-29_01](https://github.com/kalimahapps/vue-options-to-composition/assets/7331988/f47b1173-255c-4574-835b-c0af9d27b5ef)

**Comment by d9k** [comment]
Chrome version 118.0.5993.88. Doesn't work in Incognito Mode too. Both local installation and https://kalimah-apps.com/vue-options-to-composition.

Seems to be working in Firefox:

![2024_07_02__05_24_14__1504x856](https://github.com/kalimahapps/vue-options-to-composition/assets/7331988/2f0f4f6d-a542-4e27-8bfd-66ac5c536ed9)

**Comment by abdul-alhasany** [comment]
This is due to the highlighter. I updated the package and it should be working now. I will try to improve it more in the coming days to make quicker to load.
